### ISSUE TITLE
Update for iOS13 please

### ISSUE THREAD

**Issue by janedut** [DGh0st/NoBatteryIcon#1]
not support ios13

**Comment by DGh0st** [comment]
Currently there are no plans of updating this for iOS 13, as this tweak has never supported modern status bar and I don’t have an iOS 13 device that has the non-modern status bar to fix it.

The modern status bar isn’t supported because I think it has battery and charging icons as part of the same image. So hiding one without the other would require replacing the whole thing.

As to updating it only for non-modern status bar is definitely doable. Knowing how most classes and methods were renamed from iOS 12 to iOS 13, it should be as simple as finding those. However like I mentioned I don’t really have a device on iOS 13 to find those changes.

Pull Requests are always welcome if you want to take a stab at updating this.
